db:
    container_name: db
    image: postgres:9.4
    ports:
        - "5681:5432"
    environment:
        POSTGRES_USER: libreplan
        POSTGRES_PASSWORD: secret
    volumes:
        - ./sql:/docker-entrypoint-initdb.d

web:
    container_name: web
    image: libreplan/libreplan:latest
    ports:
        - "5680:8080"
    links:
        - db
